#ifndef PIGEONSMISSIONVIEWERLIB_GLOBAL_H
#define PIGEONSMISSIONVIEWERLIB_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(PIGEONSMISSIONVIEWERLIB_LIBRARY)
#  define PIGEONSMISSIONVIEWERLIBSHARED_EXPORT Q_DECL_EXPORT
#else
#  define PIGEONSMISSIONVIEWERLIBSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // PIGEONSMISSIONVIEWERLIB_GLOBAL_H
